# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flutter_test:
    name: Run flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1.5.3
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Analyze Flutter project
        run: flutter analyze
      - name: Run Flutter tests
        run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1.5.3
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Clean Flutter project
        run: flutter clean
      - name: Build Flutter app without code sign
        run: flutter build ios --no-codesign --release
      - name: Upload iOS app
        uses: actions/upload-artifact@v2.3.1
        with: 
          name: iOS
          path: build/ios/iphoneos/*.app
  
  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1.5.3
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Clean Flutter project
        run: flutter clean
      - name: Build Flutter app bundle
        run: flutter build appbundle --release
      - name: Upload android app
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Android
          path: build/app/outputs/bundle/release/*.aab
          
  build_apk:
    name: Build Flutter (Android) [APK]
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1.5.3
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Clean Flutter project
        run: flutter clean
      - name: Build Flutter app apk
        run: flutter build apk --split-per-abi --release
      - name: Upload android app apk
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Android APK
          path: build/app/outputs/apk/release/*.apk
